apiVersion: apps/v1
kind: Deployment
metadata:
  name: toys-deployment
  labels:
    app: toys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toys
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - name: toys
        image: 173506956963.dkr.ecr.us-east-1.amazonaws.com/shopping-site-toys:5e30792044ea96948f6f08bccffe0ed38dcf3b54
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: toys-service
  labels:
    app: toys
spec:
  type: ClusterIP
  selector:
    app: toys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
